name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    # Permissions for the job - extended to allow Claude to write comments and potentially more
    permissions:
      contents: read
      pull-requests: write  # Allow writing to pull requests for comments and reviews
      issues: write  # Allow writing to issues for comments
      id-token: write
      actions: read  # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Additional permissions for Claude (optional, but enabling for more capabilities)
          additional_permissions: |
            actions: read
            pull-requests: write
            issues: write

          # Enable specific tools Claude can use, tailored to the project (using bun as per rules)
          allowed_tools: "Bash(bun add:*),Bash(bun remove:*),Bash(bun install),Bash(bun run test:*),Bash(bun run check:*),Bash(bun run check:write),Bash(bun run check:unsafe),Bash(bun run build),Bash(bun run typecheck),Bash(bunx --bun shadcn@latest add:*),Bash(ls:*),Bash(cat:*),Bash(find:*),Bash(mkdir:*),Bash(touch:*),Bash(mv:*),Bash(cp:*),Bash(git add:*),Bash(git commit:*),Bash(git push:*),Bash(git pull:*),Bash(git checkout:*),Bash(git branch:*),Bash(git diff:*),Bash(git status:*),Bash(git log:*),Bash(echo:*),Bash(grep:*)"

          # Optional: Trigger when specific user is assigned to an issue
          assignee_trigger: "claude"

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"
          
          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"
          
          # Optional: Add custom instructions for Claude to customize its behavior for your project
          # custom_instructions: |
          #   Follow our coding standards
          #   Ensure all new code has tests
          #   Use TypeScript for new files
          
          # Optional: Custom environment variables for Claude
          # claude_env: |
          #   NODE_ENV: test

